name: Build LaTeX document

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:  # 👈 allows manual runs from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
