name: Build CALC LaTeX document

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if PDF exists
        id: check_pdf
        run: |
          if [ -f main.pdf ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Compile LaTeX document
        if: steps.check_pdf.outputs.exists == 'false'
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Upload PDF artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
          if-no-files-found: ignore

